/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Lluís CP - aw.lluiscerda@gmail.com
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelAutor = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButtonIniciar = new javax.swing.JButton();
        jLabelTitol = new javax.swing.JLabel();
        jLabelUsr2 = new javax.swing.JLabel();
        jLabelAny = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 51, 0));
        jButton1.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(103, 172, 104));
        jButton1.setText("Tancar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 80, 30));

        jLabelAutor.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jLabelAutor.setForeground(new java.awt.Color(103, 172, 104));
        jLabelAutor.setText("By LLCP");
        getContentPane().add(jLabelAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabelPass.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(103, 172, 104));
        jLabelPass.setText("Contrasenya");
        getContentPane().add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPassword.setBackground(new java.awt.Color(0, 51, 0));
        jPassword.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jPassword.setForeground(new java.awt.Color(103, 172, 104));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 190, -1));

        jTextField1.setBackground(new java.awt.Color(0, 51, 0));
        jTextField1.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(103, 172, 104));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 190, -1));

        jButtonIniciar.setBackground(new java.awt.Color(0, 51, 0));
        jButtonIniciar.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        jButtonIniciar.setForeground(new java.awt.Color(103, 172, 104));
        jButtonIniciar.setText("Inicia");
        jButtonIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIniciarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabelTitol.setFont(new java.awt.Font("Alef", 1, 36)); // NOI18N
        jLabelTitol.setForeground(new java.awt.Color(103, 172, 104));
        jLabelTitol.setText("CryPt3X");
        getContentPane().add(jLabelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabelUsr2.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jLabelUsr2.setForeground(new java.awt.Color(103, 172, 104));
        jLabelUsr2.setText("Usuari");
        getContentPane().add(jLabelUsr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabelAny.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jLabelAny.setForeground(new java.awt.Color(103, 172, 104));
        jLabelAny.setText("2020");
        getContentPane().add(jLabelAny, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wwallpaper.png"))); // NOI18N
        jLabelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseDragged(evt);
            }
        });
        jLabelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelFondoMousePressed(evt);
            }
        });
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -70, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
        if (JOptionPane.showConfirmDialog(null, "Esta segur de sortir?", "ALERTA!",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // SI
            System.exit(0);
        } else {
            // NO
        }
        
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jButtonIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIniciarMouseClicked
        String Usuario = "root";
        String Contrasenya = "toor";

        String Pass = new String(jPassword.getPassword());

        if (jTextField1.getText().equalsIgnoreCase(Usuario) && Pass.equals(Contrasenya)) {
            Interfa2 GN = new Interfa2();
            GN.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuari / Contrasenya erronis");
        }
    }//GEN-LAST:event_jButtonIniciarMouseClicked
    
    int xx, xy;
    private void jLabelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMousePressed
        xx = evt.getX();
        xy = evt.getX();    }//GEN-LAST:event_jLabelFondoMousePressed

    private void jLabelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xx, y-xy);    }//GEN-LAST:event_jLabelFondoMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabelAny;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelTitol;
    private javax.swing.JLabel jLabelUsr2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
