/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Utiles.Utiles;

/**
 *
 * @author Lluís CP - aw.lluiscerda@gmail.com
 */
public class Interfa2 extends javax.swing.JFrame {

    /**
     * Creates new form Interfa2
     */
    public Interfa2() {
        initComponents();
        this.setLocationRelativeTo(null);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton21 = new javax.swing.JButton();
        jButtonCrear = new javax.swing.JButton();
        jButtonOcultar = new javax.swing.JButton();
        jButtonRevertir = new javax.swing.JButton();
        jButtonRmdir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabelAutor = new javax.swing.JLabel();
        jLabelTitol = new javax.swing.JLabel();
        jLabelAny = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton21.setBackground(new java.awt.Color(0, 51, 0));
        jButton21.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        jButton21.setForeground(new java.awt.Color(103, 172, 104));
        jButton21.setText("Tancar");
        jButton21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 80, 30));

        jButtonCrear.setBackground(new java.awt.Color(0, 51, 0));
        jButtonCrear.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        jButtonCrear.setForeground(new java.awt.Color(103, 172, 104));
        jButtonCrear.setText("Crear Carpeta");
        jButtonCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 30));

        jButtonOcultar.setBackground(new java.awt.Color(0, 51, 0));
        jButtonOcultar.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        jButtonOcultar.setForeground(new java.awt.Color(103, 172, 104));
        jButtonOcultar.setText("Ocultar");
        jButtonOcultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcultarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 30));

        jButtonRevertir.setBackground(new java.awt.Color(0, 51, 0));
        jButtonRevertir.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        jButtonRevertir.setForeground(new java.awt.Color(103, 172, 104));
        jButtonRevertir.setText("Revertir");
        jButtonRevertir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRevertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRevertirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRevertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 30));

        jButtonRmdir.setBackground(new java.awt.Color(0, 51, 0));
        jButtonRmdir.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        jButtonRmdir.setForeground(new java.awt.Color(103, 172, 104));
        jButtonRmdir.setText("Eliminar Directori Hidden");
        jButtonRmdir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRmdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRmdirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRmdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 30));

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 51, 0));
        jTextPane1.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(103, 172, 104));
        jTextPane1.setAutoscrolls(false);
        jTextPane1.setCaretColor(new java.awt.Color(0, 51, 0));
        jTextPane1.setDisabledTextColor(new java.awt.Color(0, 51, 0));
        jTextPane1.setSelectedTextColor(new java.awt.Color(0, 51, 0));
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, 80));

        jLabelAutor.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jLabelAutor.setForeground(new java.awt.Color(103, 172, 104));
        jLabelAutor.setText("By LLCP");
        getContentPane().add(jLabelAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabelTitol.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jLabelTitol.setForeground(new java.awt.Color(103, 172, 104));
        jLabelTitol.setText("asdasdasd");
        getContentPane().add(jLabelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 240, 60));

        jLabelAny.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jLabelAny.setForeground(new java.awt.Color(103, 172, 104));
        jLabelAny.setText("2020");
        getContentPane().add(jLabelAny, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoo.jpg"))); // NOI18N
        jLabel22.setText("Crear Carpeta");
        jLabel22.setInheritsPopupMenu(false);
        jLabel22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel22MouseDragged(evt);
            }
        });
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        String respuesta;

        respuesta = Utiles.deseaSalir();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        Utiles.carpeta();

    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonRmdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRmdirActionPerformed
        Utiles.Borrar();
    }//GEN-LAST:event_jButtonRmdirActionPerformed

    private void jButtonRevertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRevertirActionPerformed
        Utiles.Pass();
     
    }//GEN-LAST:event_jButtonRevertirActionPerformed

    private void jButtonOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcultarActionPerformed
        Utiles.Renombre();
        Utiles.Cmd();
    }//GEN-LAST:event_jButtonOcultarActionPerformed
int xx,xy;
    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        xx=evt.getX();
        xy=evt.getX();
    }//GEN-LAST:event_jLabel22MousePressed

    private void jLabel22MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseDragged
      int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xx, y-xy);     }//GEN-LAST:event_jLabel22MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfa2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonOcultar;
    private javax.swing.JButton jButtonRevertir;
    private javax.swing.JButton jButtonRmdir;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabelAny;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelTitol;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
